name: "Upload file to http server"
description: "Upload file to http server"
inputs:
  server: # id of input
    description: "upload api"
    required: true
  file:
    required: true
  rename-file-to:
    default: ""
  field-name:
    required: true
    default: "file"
  debug:
    default: false
outputs:
  file: # id of output
    description: "The new filename"
runs:
  using: "node12"
  main: "dist/index.js"
