name: "Upload file to http(s) server"
description: "Upload file to http(s) server"
author: Kaven[kaven@wuwenkai.com]
branding:
  icon: "arrow-up-circle"
  color: "blue"
inputs:
  server: # id of input
    description: "upload api"
    required: true
  file:
    required: true
  rename-file-to:
    default: ""
  field-name:
    required: true
    default: "file"
  debug:
    default: false
  json_stringify_form_data:
    # '[{"key":"k1","value":"v1"},{"key":"k2","value":"v2"}]'
    default: '[]'

outputs:
  file: # id of output
    description: "The new filename"
runs:
  using: "node16"
  main: "dist/index.js"
