name: Self Test

on:
  workflow_dispatch:

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: Test
    steps:
      - name: Upload test
        id: upload
        uses: Kaven-Universe/upload-to-kaven-file-server@v1.0.7
        with:
          server: "http://122.234.162.107:5807/file"
          file: "index.js"
      # Use the output from the `upload` step
      - name: Get the output time
        run: echo "The time was ${{ steps.upload.outputs.time }}"
