name: Self Test

on:
  workflow_dispatch:

jobs:
  upload_job:
    runs-on: ubuntu-latest
    name: Test
    steps:
      - name: Get current time
        id: current_date_time
        uses: Kaven-Universe/github-action-current-date-time@v1.0.3
        with:
          format: "YYYY_MM_DD_HH_mm_ss"
          timezone-offset: -480
      - name: Upload
        id: upload
        uses: Kaven-Universe/upload-to-kaven-file-server@v1.0.10
        with:
          server: "http://122.225.206.26:3001/file"
          file: ""
          rename-file-to: "self test[${{ steps.current_date_time.outputs.time }}].txt"
          debug: true
      # Use the output from the `upload` step
      - name: Get the output
        run: echo "${{ steps.upload.outputs.file }}"
